// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./../layouts/components/header/components/BreadCrumb.vue')['default']
    Home: typeof import('./../components/Home.vue')['default']
    'IconMdi:formatIndentDecrease': typeof import('~icons/mdi/format-indent-decrease')['default']
    'IconMdi:formatIndentIncrease': typeof import('~icons/mdi/format-indent-increase')['default']
    MenuCollapse: typeof import('./../layouts/components/header/components/MenuCollapse.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideLogo: typeof import('./../layouts/components/sidebar/components/SideLogo.vue')['default']
    SideMenu: typeof import('./../layouts/components/sidebar/components/SideMenu.vue')['default']
    Tag: typeof import('./../layouts/components/tag/components/tag.vue')['default']
  }
}
